---
functional:
  - На сайте должна быть доступна регистрация с помощью GitHub, Discord, Email
  - На сайте должна быть доступна авторизация с помощью GitHub, Discord, Email
  - Пользователь может играть со случайным противникои
  - Пользователь может послать другу ссылку для соревнования с ним
  - Пользователь может соревноваться с ботом
  - Пользователь должен видеть код соперника
  - Пользователь имеет возможность писать код на JavaScript, PHP, Python и Ruby
  - Пользователь должен видеть результаты запуска тестов
  - Пользователю доступны 4 уровня сложности на выбор
  - Пользователь может создать игру самостоятельно
  - Соперник может подключиться к созданной пользователем игре
  - Пользователь может вступать в открытые игры
  - Пользователь может зайти в запущенную игру в качестве зрителя
  - Пользователь может видеть свой рейтинг
  - Сайт должен иметь чат для общения пользователя с соперником и зрителями
  - Пользователь может установить расширение для Chrome
  - Сайт нужно протестировать на совместимость с последними версиями браузеров
  - Сайт должен иметь мобильную версию
  - Сайт должен быть доступен на различных устройствах
  
non-functional:
  - Сайт должен быть безопасным и защищать данные пользователя
  - Сайт должен быть разработан с учетом удобства использования и оптимизирован для скорости работы
  - Сайт должен быть удобным на мобильном устройстве
  - Сайт должен быть способен обрабатывать большое количество трафика (1000 одновременных пользователей)

implicit:
  - требование 5
  - требование 6
