---
functional:
  - На сайте должна быть доступна регистрация с помощью GitHub, Discord, Email
  - На сайте должна быть доступна авторизация с помощью GitHub, Discord, Email
  - Пользователь может создать игру для соревнований со случайным соперником
  - Пользователь может пригласить друга в созданную игру
  - Пользователь может поделиться ссылкой для приглашения в игру
  - Пользователь может соревноваться с ботом
  - Пользователь должен видеть код соперника
  - Пользователь должен видеть результаты запуска тестов
  - Пользователю доступны 4 уровня сложности на выбор
  - Пользователь может создать игру самостоятельно
  - Соперник может подключиться к созданной пользователем игре
  - Пользователь может вступать в открытые игры
  - Пользователь может зайти в запущенную игру в качестве зрителя
  - Пользователь может видеть свой рейтинг
  - Сайт должен иметь чат для общения пользователя с соперником и зрителями
  - Пользователь может установить расширение для Chrome
  - Сайт нужно протестировать на совместимость с последними версиями браузеров
  - Сайт должен иметь мобильную версию
  - Сайт должен быть доступен на различных устройствах
  
non-functional:
  - Сайт должен быть безопасным и защищать данные пользователя
  - Сайт должен быть разработан с учетом удобства использования и оптимизирован для скорости работы
  - Сайт должен быть удобным на мобильном устройстве
  - Сайт должен быть способен обрабатывать большое количество трафика (1000 одновременных пользователей)

implicit:
  - Интерфейс должен быть интуитивно понятным и простым в навигации
  - Время загрузки сайта должно быть минимальным для обеспечения хорошего пользовательского опыта
  - Сайт должен соответствовать стандартам доступности для людей с ограниченными возможностями
  - Должна быть возможность быстро и легко связаться с разработчиками
  - Сайт должен иметь форму обратной связи
  - Сайт должен иметь многоязычную функциональность, если это необходимо для целевой аудитории
  - Система должна информировать пользователей о новых вызовах, завершении боев или достижениях в игре
  - Сайт должен поддерживать множество языков программирования и обеспечивать возможность легкого добавления новых
  - Nickname при регистрации должен содержать от 3 до 16 символов
  - Nickname должен состоять из латинских букв, цифр и символов подчеркивания
  - Nickname должен начинаться только с латинской буквы
  - Пароль при регистрации должен содержать от 6 до 16 символов
  - Пароль при регистрации должен содержать хотя бы 1 специальный символ
  - Должна быть возможность восстановления пароля
