---
functional:
  - На сайте должна быть доступна авторизация с помощью GitHub
  - Пользователь может играть со случайным противникои
  - Пользователь может послать другу ссылку для соревнования с ним
  - Пользователь может соревноваться с ботом
  - Доступные языки программирования JavaScript, PHP, Python и Ruby
  - Пользователю доступны 4 уровня сложности на выбор
  - Пользователь может создать игру самостоятельно
  - Соперник может подключиться к созданной пользователем игре
  - Пользователь может вступать в открытые игры
  - Пользователь может зайти в запущенную игру в качестве зрителя
  - Пользователь может установить расширение для Chrome
  - Сайт нужно протестировать на совместимость с последними версиями браузеров
non-functional:
  - Сайт должен быть безопасным и защищать данные пользователя
  - требование 4
implicit:
  - требование 5
  - требование 6
